Serverbooking/Models/BookingInfoesCRUDController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Serverbooking.Models
{
    public class BookingInfoesCRUDController : Controller
    {
        private ServerInfoEntities db = new ServerInfoEntities();

        // GET: BookingInfoesCRUD
        public async Task<ActionResult> BookingData()
        {
            var bookingInfo = db.BookingInfo.Include(b => b.InfoServer);
            return View(await bookingInfo.ToListAsync());
        }

        // GET: BookingInfoesCRUD/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingInfo bookingInfo = await db.BookingInfo.FindAsync(id);
            if (bookingInfo == null)
            {
                return HttpNotFound();
            }
            return View(bookingInfo);
        }

        // GET: BookingInfoesCRUD/Create
        public ActionResult Create()
        {
            ViewBag.ServerID = new SelectList(db.InfoServers, "ServerID", "Status");
            return View();
        }

        // POST: BookingInfoesCRUD/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "BookingID,ServerID,UserID,CheckInTime,CheckOutTime")] BookingInfo bookingInfo)
        {
            if (ModelState.IsValid)
            {
                db.BookingInfo.Add(bookingInfo);
                await db.SaveChangesAsync();
                return RedirectToAction("BookingData");
            }

            ViewBag.ServerID = new SelectList(db.InfoServers, "ServerID", "Status", bookingInfo.ServerID);
            return View(bookingInfo);
        }

        // GET: BookingInfoesCRUD/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingInfo bookingInfo = await db.BookingInfo.FindAsync(id);
            if (bookingInfo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ServerID = new SelectList(db.InfoServers, "ServerID", "Status", bookingInfo.ServerID);
            return View(bookingInfo);
        }

        // POST: BookingInfoesCRUD/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "BookingID,ServerID,UserID,CheckInTime,CheckOutTime")] BookingInfo bookingInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookingInfo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("BookingData");
            }
            ViewBag.ServerID = new SelectList(db.InfoServers, "ServerID", "Status", bookingInfo.ServerID);
            return View(bookingInfo);
        }

        // GET: BookingInfoesCRUD/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingInfo bookingInfo = await db.BookingInfo.FindAsync(id);
            if (bookingInfo == null)
            {
                return HttpNotFound();
            }
            return View(bookingInfo);
        }

        // POST: BookingInfoesCRUD/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            BookingInfo bookingInfo = await db.BookingInfo.FindAsync(id);
            db.BookingInfo.Remove(bookingInfo);
            await db.SaveChangesAsync();
            return RedirectToAction("BookingData");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Serverbooking/Controllers/ServerInfoCRUDController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Serverbooking.Models
{
    public class ServerInfoCRUDController : Controller
    {
        private ServerInfoEntities db = new ServerInfoEntities();

        // GET: CRUD
        public async Task<ActionResult> ServerData()
        {
            return View(await db.InfoServers.ToListAsync());
        }
        public async Task<ActionResult> BookingData()
        {
            var bookingInfo = db.BookingInfo.Include(b => b.InfoServer);
            return View(await bookingInfo.ToListAsync());
        }

        // GET: CRUD/Details/5
        public async Task<ActionResult> ServerDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InfoServer infoServer = await db.InfoServers.FindAsync(id);
            if (infoServer == null)
            {
                return HttpNotFound();
            }
            return View(infoServer);
        }

        // GET: CRUD/Create
        public ActionResult ServerCreate()
        {
            return View();
        }

        // POST: CRUD/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ServerCreate([Bind(Include = "ServerID,Status,ServerName,Environment,ActiveBookingID,UserID")] InfoServer infoServer)
        {
            if (ModelState.IsValid)
            {
                db.InfoServers.Add(infoServer);
                await db.SaveChangesAsync();
                return RedirectToAction("ServerData");
            }

            return View(infoServer);
        }

        // GET: CRUD/Edit/5
        public async Task<ActionResult> ServerEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InfoServer infoServer = await db.InfoServers.FindAsync(id);
            if (infoServer == null)
            {
                return HttpNotFound();
            }
            return View(infoServer);
        }

        // POST: CRUD/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ServerEdit([Bind(Include = "ServerID,Status,ServerName,Environment,ActiveBookingID,UserID")] InfoServer infoServer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(infoServer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("ServerData");
            }
            return View(infoServer);
        }
        
        // GET: CRUD/Delete/5
        public async Task<ActionResult> ServerDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InfoServer infoServer = await db.InfoServers.FindAsync(id);
            if (infoServer == null)
            {
                return HttpNotFound();
            }
            return View(infoServer);
        }

        // POST: CRUD/Delete/5
        [HttpPost, ActionName("ServerDelete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            InfoServer infoServer = await db.InfoServers.FindAsync(id);
            db.InfoServers.Remove(infoServer);
            await db.SaveChangesAsync();
            return RedirectToAction("ServerData");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Serverbooking/Views/ServerInfoCRUD/Create.cshtml
@model Serverbooking.Models.InfoServer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Server Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ServerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Environment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Environment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Environment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveBookingID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActiveBookingID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActiveBookingID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ServerData")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Serverbooking/Views/ServerInfoCRUD/Delete.cshtml
@model Serverbooking.Models.InfoServer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Server Information</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Environment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Environment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActiveBookingID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveBookingID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ServerData")
        </div>
    }
</div>

Serverbooking/Views/ServerInfoCRUD/Details.cshtml
@model Serverbooking.Models.InfoServer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Server Information</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Environment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Environment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActiveBookingID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveBookingID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ServerID }) |
    @Html.ActionLink("Back to List", "ServerData")
</p>

Serverbooking/Views/ServerInfoCRUD/Edit.cshtml
@model Serverbooking.Models.InfoServer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Server Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ServerID)

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Environment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Environment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Environment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveBookingID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActiveBookingID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActiveBookingID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ServerData")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Serverbooking/Views/ServerInfoCRUD/ServerCreate.cshtml
@model Serverbooking.Models.InfoServer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Server Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ServerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Environment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Environment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Environment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveBookingID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActiveBookingID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActiveBookingID, "", new { @class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" >
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control", @Value = @Environment.UserName } })
                
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ServerData")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval") 
}

Serverbooking/Views/ServerInfoCRUD/ServerData.cshtml
@model IEnumerable<Serverbooking.Models.InfoServer>

@{
    ViewBag.Title = "Index";
}


<link href="~/Content/Tables.css" rel="stylesheet" type="text/css" />
<br />
<h2>Server Information</h2>



<link href="~/Content/Tabs.css" rel="stylesheet" type="text/css" />
<body>



    <ul class="tab">
        <li><a href="#" class="tablinks" onclick="openServer(event, 'RMS')">RMS</a></li>
        <li><a href="#" class="tablinks" onclick="openServer(event, 'AIR')">AIR</a></li>
        <li><a href="#" class="tablinks" onclick="openServer(event, 'DQT')">DQT</a></li>
        <li><a href="#" class="tablinks" onclick="openServer(event, 'TMROW')">TMROW</a></li>
        <li><a href="#" class="tablinks" onclick="openServer(event, 'CAT_Workstation')">CAT Workstation</a></li>
    </ul>

    <div id="RMS" class="tabcontent">
        <h3>RMS</h3>
        <p>
            <table>
                <tr>
                    <th>
                        ServerID
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        ServerName
                    </th>
                    <th>
                        Environment
                    </th>

                    <th>
                        UserName
                    </th>
                    <th>
                        @Html.ActionLink("Book A Server", "BookingCreate", "BookingInfoesCRUD", null,  new { @style = "color: #ffffff;"})
                    </th>
                    <th> </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.ServerID
                        </td>
                        <td>
                            @item.Status
                        </td>
                        <td>
                            @item.ServerName
                        </td>
                        <td>
                            @item.Environment
                        </td>
                        <td>
                           @item.UserID
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "ServerEdit", new { id = item.ServerID }) |
                            @Html.ActionLink("Details", "ServerDetails", new { id = item.ServerID }) |
                            @Html.ActionLink("Delete", "ServerDelete", new { id = item.ServerID })
                        </td>

                    </tr>
                }

            </table>
        <p>
            @Html.ActionLink("Create New", "ServerCreate", new { })
        </p><br />
    </div>

    <div id="AIR" class="tabcontent">
        <h3>AIR</h3>

    </div>

    <div id="DQT" class="tabcontent">
        <h3>DQT</h3>

    </div>

    <div id="TMROW" class="tabcontent">
        <h3>TMROW</h3>

    </div>

    <div id="CAT_Workstation" class="tabcontent">
        <h3>CAT Workstation</h3>

    </div>

    
    <script>
        function openServer(evt, serverName) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(serverName).style.display = "block";
            evt.currentTarget.className += " active";
        }
    </script>

</body>

Serverbooking/Views/ServerInfoCRUD/ServerDelete.cshtml
@model Serverbooking.Models.InfoServer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Server Information</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Environment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Environment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActiveBookingID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveBookingID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ServerData")
        </div>
    }
</div>

Serverbooking/Views/ServerInfoCRUD/ServerDetails.cshtml
@model Serverbooking.Models.InfoServer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Server Information</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Environment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Environment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActiveBookingID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveBookingID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "ServerEdit", new { id = Model.ServerID }) |
    @Html.ActionLink("Back to List", "ServerData")
</p>

Serverbooking/Views/ServerInfoCRUD/ServerEdit.cshtml
@model Serverbooking.Models.InfoServer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Server Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ServerID)

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Environment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Environment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Environment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveBookingID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActiveBookingID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActiveBookingID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ServerData")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}